### ISSUE TITLE
Make API variable examples more accessible

### ISSUE THREAD

**Issue by TehShrike** [origamitower/folktale#1]
I'm not hip with all the Monad slang, so this documentation is fairly opaque to me: http://docs.folktalejs.org/en/latest/api/data/task/Task.html
- are α and β and γ placeholders for something meaningful-yet-ungoogleable, or are they just trendy placeholders akin to foo/bar/baz?
- if they have specific meanings, what are they?
- what is the meaning of `@Task` and `=>` and `→`?  I'm guessing that the `=>` indicates a function and the following `(β → γ)` indicates that the function takes a `β` and returns a `γ`, but I'm not sure.

The text below each method would probably be sufficient if I understood the shorthand above, but it's not enough to get the point across by itself when I don't understand the shorthand.

I don't think the shorthand necessarily needs to be removed or anything, I just need an example showing what the shorthand expands to in actual JavaScript.

**Comment by robotlolita** [comment]
Yeah, I need to write the appendix on the type notation used by those signatures.

In general, it's something fairly similar to Haskell's type notation, but:

- greek letters are used for type variables (so instead of `forall a. forall b. a → b` you have `α → β`). 
- `a → b` means something that takes in type `a` and returns type `b`.
- `p => a` means something that has type `a`, as long as it fulfils the predicates dictated in `p`. `@x` is a predicate that dictates that the type of `this` in the type expression must be `x`. `a:b` declares `a` as an alias for type `b`. `t(_)` is a partially applied type `t`.
- `a | b` is a type union, which means it can be either type `a` or type `b`.
- `a :: b` means that while something is of type `a`, evaluating it will cause the effects described in `b` (it isn't a pure computation).
- `{ a: b }` is an object type with property `a` having type `b`.
- `{ α | b }` is a row type, which matches the object type `b`, and stores any properties not covered by that type in the variable `α`.
