### ISSUE TITLE
Getting Started Documentation

### ISSUE THREAD

**Issue by LandonSchropp** [origamitower/folktale#132]
I'm brand new to Folktale. After reading the website's homepage, I wanted to learn more about the library, so I clicked on the Get Started button. This took me to the Docs page, but unfortunately, the links on that page weren't all that helpful:

* What's New? 
* Installing
* API Reference
* Known Issues
* Migrating From...
* Changelog

What I'm really looking for is a **Getting Started** guide to be front and center. In particular, it would be great if it could answer these questions:

* What is Folktale?
* Why would I use it?
* What are the high-level concepts?
* What are some basic examples of using Folktale?

My next stop was Google, where I found [this guide](http://folktalegithubio.readthedocs.io/en/latest/quickstart/index.html) from the 1.0 version of the library. That's much more helpful, but it's also out of date, and it still doesn't answer all my questions.

**Comment by robotlolita** [comment]
Yeah, the landing page needs to be more helpful.

The documentation actually answers those questions right now, but instead of presenting them as a linear document that you can follow, or as cross-referenced sections, it has that conceptual documentation inside the API reference pages, on each submodule. This is quite messy and hard to navigate, I'll agree, but fixing this involves fixing some of the documentation tooling as well, so that'll take some time to solve.

I suppose a small "Overview" page could lessen this problem by linking to pages inside the API reference. This is not ideal, but at least would give people a way to see what's in the library and links to detailed information on each concept.

Conceptual pages for the modules are:

  - [core/lambda](http://folktale.origamitower.com/api/v2.0.0/en/folktale.core.lambda.html) - tools for transforming and combining functions.
  - [core/object](http://folktale.origamitower.com/api/v2.0.0/en/folktale.core.object.html) - utilities for working with objects as dictionaries and records.
  - [adt/union](http://folktale.origamitower.com/api/v2.0.0/en/folktale.adt.union.union.union.html) - modelling possibilities in data in a functional way.
  - [validation](http://folktale.origamitower.com/api/v2.0.0/en/folktale.validation.html) - a data structure that typically models form validations, and other scenarios where you want to aggregate all failures, rather than short-circuit if an error happens.
  - [result](http://folktale.origamitower.com/api/v2.0.0/en/folktale.result.html) - A data structure that models the result of operations that may fail.
  - [maybe](http://folktale.origamitower.com/api/v2.0.0/en/folktale.maybe.html) - A data structure that models the presence or absence of a value.
  - [concurrency/task](http://folktale.origamitower.com/api/v2.0.0/en/folktale.concurrency.task.html) - A data structure that models asynchronous actions, supporting safe cancellation and automatic resource handling.

These pages all follow the same basic structure. They start with a short description of what the module does, followed by a small example, followed by why they're useful, some use cases, and where relevant details on internal architecture and comparisons with other modules in the library. But, again, the tool used to generate those pages makes them really hard to navigate/discover :(

I'll try writing an overview page later this week. But solving the rest of the issues with the docs is going to take a bit more of time.

**Comment by LandonSchropp** [comment]
Thanks for the reply! Even those short summaries are really helpful in revealing the intent of this library. I think the changes you suggested would be really helpful to somebody new to this package.

Thanks again!
