### ISSUE TITLE
Hang when exception thrown in `chain`

### ISSUE THREAD

**Issue by ron-liu** [origamitower/folktale#156]
When there are some exceptions thrown in `chain`, it will not reject or resolve, it just hang without any helpful information.

### Steps to reproduce
Given the following example, it didn't resolve or reject till timeout.
```javascript
import {task, of} from 'folktale/concurrency/task'
test.only('exception', async () => {
	await task(({resolve, reject}) => setTimeout( ()=>resolve(1) , 10))
	.chain(x=> {
		throw 'error' // emulate some errors
		return of(2)
	})
	.run()
	.promise()
})
// Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
```
#### Expected behaviour
I hope when exception thrown, it shall reject automatically.

### Environment
  - OS: macOS 10.12.6
  - JavaScript VM: 8
  - Folktale version: 2

### Additional information
The following test will be rejected straight away
```javascript
import {task, of} from 'folktale/concurrency/task'
test.only('exception', async () => {
	await of(1)
	.chain(x=> {
		throw 'error' // emulate some errors by typo or something
		return of(2)
	})
	.run()
	.promise()
})
```

**Comment by robotlolita** [comment]
Ah, yes, unlike Promises, Task won't catch errors for you automatically. You need to wrap those parts in a `try/catch` and handle them accordingly. I just realised this isn't documented, but it's a deliberate design decision.

In general, I believe that if some exceptional condition that you weren't expecting happens at runtime, your program should crash, then restart in a clean, well-known state. If your program continues to run, you don't know in which state you are anymore, or even if that's a valid state in your program. That's extremely dangerous since you can't predict your program's behaviour. [The node documentation does a good job at explaining the dangers of catch-and-continue](https://nodejs.org/dist/latest-v8.x/docs/api/domain.html#domain_warning_don_t_ignore_errors) that Promises use.

Catching errors automatically has some other issues in that errors thrown asynchronously can't be caught (the stack frames when the error is thrown is not under the function that started the process anymore).

While the example you posted should _crash_ the process, from what I understood it's not doing that, and instead it's just not completing the test case instead. That may be your test runner handling these errors for you (e.g.: with [`process.on('uncaughtException')`](https://nodejs.org/dist/latest-v8.x/docs/api/process.html#process_warning_using_uncaughtexception_correctly)). If you run it directly it crashes the process, as expected:

![capturar](https://user-images.githubusercontent.com/406477/30789299-e1e8c1aa-a17a-11e7-8ba2-345bf7587e8b.PNG)

**Comment by ron-liu** [comment]
@robotlolita yeah, the issue is from jest, I think. I tried same test on mocha, it is fine. 

I will update if I solve the jest issue.

**Comment by ron-liu** [comment]
Fixed the  issue, I just need to add `--env node` when run `jest`, check [this jest issue link](https://github.com/facebook/jest/issues/2059#issuecomment-332254817) for more details.

The issue is not related with folktale, all because of the test runner I am using.
