### ISSUE TITLE
Don't publish dev-mode code to npm

### ISSUE THREAD

**Issue by robotlolita** [origamitower/folktale#32]
See https://github.com/folktale/data.task/issues/36

**Comment by sotojuan** [comment]
I can take care of this! But I would argue using a whitelist instead of a blacklist (`npmignore`) would be better. `package.json` allows a `file` array which lists files to include and it acts as a whitelist. Some stuff like `readme` is *always* added so we don't have to worry about that.

I'd argue that's a cleaner way to do it but don't mind adding stuff to `npmignore` either.

**Comment by robotlolita** [comment]
Oh, I didn't know about `files`. But that sounds good to me.
