### ISSUE TITLE
Is Documentation broken?

### ISSUE THREAD

**Issue by rajaraodv** [origamitower/folktale#54]
http://origamitower.github.io/folktale has no links to go through various Monads and stuff.

**Comment by robotlolita** [comment]
The work on this repo is pretty much WIP at this point. Documentation is one of the things that needs the most amount of work right now. Docs for the upcoming alpha release are being worked on at https://github.com/origamitower/folktale/commits/patch/docs, but Maybe and Validation docs are still missing (haven't had time to work on them this month due to my day job)

**Comment by rajaraodv** [comment]
I see. Thanks!
