### ISSUE TITLE
Aggregating errors with Either vs Validation

### ISSUE THREAD

**Issue by OliverJAsh** [origamitower/folktale#78]
I'm new to functional programming, and after reading [Professor Frisby's Mostly Adequate Guide to Functional Programming](https://drboolean.gitbooks.io/mostly-adequate-guide/), I'm finding folktale a brilliant resource to put my learnings into practice—so thank you! 😄 

I understand one of the main benefits of Validation, being an applicative functor and not a monad, is that you can aggregate errors. However, it seems that it is actually possible to aggregate errors using Either by defining a `collect` function as follows.

Am I missing something here?

``` ts
const collectEithers = eithers => (
    eithers
        .reduce((acc, either) => (
            acc.fold(
                accLeft => either.fold(
                    left => Either.Left(accLeft.concat(left)),
                    right => Either.Left(accLeft)
                ),
                accRight => either.fold(
                    left => Either.Left([left]),
                    right => Either.Right(accRight.concat(right))
                )
            )
        ), Either.Right([]))
)
```

**Comment by robotlolita** [comment]
Oh, you can always write a specific function to do something with a data structure (aggregating errors in Eithers in this case). The difference is mostly that Validation implements this kind of behaviour in an interface (Applicative), so anything that uses that interface will get this behaviour, and you can think about your program in terms of these interface (it's simpler to understand how each piece interacts with each other because interactions are well-defined in the interface).

**Comment by OliverJAsh** [comment]
Thanks for the answer @robotlolita. That makes sense :-)
